# Copyright 2026 Sheel Morjaria
# SPDX-License-Identifier: Apache-2.0
"""Declarative cross-interface capability registry.

The migration is intentionally incremental: every MCP exposure is listed here,
while high-drift commands move their argparse schema here one at a time.  A
capability cannot be registered on MCP without a registry entry.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from typing import Any


MCP_EFFECTS = frozenset({
    "workspace_read",
    "workspace_write_new",
    "external_execution",
    "provider_access",
    "evidence_publication",
    "service_state_read",
    "service_state_write",
    "remote_worker_dispatch",
})
MCP_OUTPUT_SCOPES = frozenset({
    "none", "designated-new-artifacts", "immutable-evidence-only",
})


@dataclass(frozen=True)
class ArgumentSpec:
    flags: tuple[str, ...]
    kwargs: dict[str, Any]


@dataclass(frozen=True)
class ClaimStage:
    claim: str
    minimum_step: int


@dataclass(frozen=True)
class MilestoneMetadata:
    lane: str
    deployment_split: str
    required_judges: tuple[str, ...]
    claims: tuple[ClaimStage, ...]
    claims_forbidden: tuple[str, ...]
    assumptions: tuple[str, ...]
    deployment_profiles: tuple[str, ...]
    hardware_profiles: tuple[str, ...]
    artifact_hash_bindings: tuple[str, ...]
    maturity_from: str
    maturity_to: str
    maturity_requires_step: int
    current_step: int
    step_status: str
    current_maturity: str
    completed_claims: tuple[str, ...]


@dataclass(frozen=True)
class MCPInvocationProfile:
    """One precisely admitted MCP command/mode/backend combination."""

    name: str
    modes: tuple[str, ...]
    languages: tuple[str, ...]
    backends: tuple[str, ...]
    effects: tuple[str, ...]
    required_effects: tuple[str, ...] = ()
    providers: tuple[str, ...] = ()
    output_scope: str = "none"
    evidence: str = "none"


@dataclass(frozen=True)
class CapabilitySpec:
    name: str
    description: str
    cli_command: str | None = None
    mcp_tool: str | None = None
    arguments: tuple[ArgumentSpec, ...] = ()
    epistemic_boundary: str = "No claim is minted without its named judge."
    trust_action: bool = False
    milestone: MilestoneMetadata | None = None
    mcp_isolation: str = "unsupported"
    mcp_profiles: tuple[MCPInvocationProfile, ...] = ()


def _capability(value: dict[str, Any]) -> CapabilitySpec:
    """Decode an external package's data-only capability declaration."""
    milestone_value = value.get("milestone")
    milestone = None
    if milestone_value is not None:
        milestone_data = dict(milestone_value)
        milestone_data["claims"] = tuple(
            ClaimStage(**claim) if isinstance(claim, dict) else claim
            for claim in milestone_data.get("claims", ())
        )
        milestone = MilestoneMetadata(**milestone_data)
    arguments = tuple(
        ArgumentSpec(tuple(argument["flags"]), dict(argument.get("kwargs", {})))
        if isinstance(argument, dict)
        else argument
        for argument in value.get("arguments", ())
    )
    mcp_isolation = value.get("mcp_isolation", "unsupported")
    if mcp_isolation not in {
            "a2a-coordination", "non-executing", "strict-java",
            "strict-execution", "unsupported"}:
        raise ValueError(f"unknown MCP isolation profile: {mcp_isolation}")
    mcp_profiles = tuple(
        MCPInvocationProfile(
            name=profile["name"],
            modes=tuple(profile.get("modes", ())),
            languages=tuple(profile.get("languages", ())),
            backends=tuple(profile.get("backends", ())),
            effects=tuple(profile.get("effects", ())),
            required_effects=tuple(profile.get("required_effects", ())),
            providers=tuple(profile.get("providers", ())),
            output_scope=profile.get("output_scope", "none"),
            evidence=profile.get("evidence", "none"),
        )
        for profile in value.get("mcp_profiles", ())
    )
    if value.get("trust_action", False) and mcp_profiles:
        raise ValueError("human trust actions cannot have MCP invocation profiles")
    if mcp_isolation != "unsupported" and not mcp_profiles:
        raise ValueError("admitted MCP capabilities require an invocation profile")
    for profile in mcp_profiles:
        unknown_effects = sorted(set(profile.effects) - MCP_EFFECTS)
        if unknown_effects:
            raise ValueError("unknown MCP profile effects: " + ", ".join(unknown_effects))
        if not set(profile.required_effects).issubset(profile.effects):
            raise ValueError("required MCP effects must be within the profile ceiling")
        if profile.output_scope not in MCP_OUTPUT_SCOPES:
            raise ValueError(f"unknown MCP output scope: {profile.output_scope}")
        if profile.providers and "provider_access" not in profile.effects:
            raise ValueError("MCP providers require the provider_access effect")
        if "provider_access" in profile.effects and not profile.providers:
            raise ValueError("MCP provider_access requires an explicit provider allowlist")
        if mcp_isolation == "non-executing" and \
                "external_execution" in profile.effects:
            raise ValueError("non-executing MCP profiles cannot authorize execution")
        if "remote_worker_dispatch" in profile.effects and \
                mcp_isolation != "a2a-coordination":
            raise ValueError(
                "remote worker dispatch requires A2A coordination isolation")
        if mcp_isolation == "a2a-coordination" and \
                set(profile.effects) & {"external_execution", "provider_access"}:
            raise ValueError(
                "A2A coordination cannot acquire local execution or provider access")
        if "workspace_write_new" in profile.effects and \
                profile.output_scope != "designated-new-artifacts":
            raise ValueError("MCP workspace writes require a designated output scope")
    return CapabilitySpec(
        name=value["name"],
        description=value["description"],
        cli_command=value.get("cli_command"),
        mcp_tool=value.get("mcp_tool"),
        arguments=arguments,
        epistemic_boundary=value.get(
            "epistemic_boundary", "No claim is minted without its named judge."
        ),
        trust_action=value.get("trust_action", False),
        mcp_isolation=mcp_isolation,
        mcp_profiles=mcp_profiles,
        milestone=milestone,
    )


_MCP_TOOLS = (
    "verify_code",
    "validate_architecture",
    "implement_code",
    "inspect_code",
    "analyze_codebase",
    "document_code",
    "assess_security",
    "security_inspect",
    "security_exploit",
    "remediate_code",
    "correct_behavior",
    "apply_refactor",
    "verify_refactor",
    "verify_bisimulation",
    "optimize_algorithm",
    "discover_algorithms",
    "validate_domain",
    "compose",
    "reverify_composition",
    "unified_system",
    "draft_canonical_contract",
    "architecture",
    "system",
    "prove_equivalence",
    "generate_traceability_matrix",
    "verify_unbounded",
    "verify_linearizability",
    "verify_distributed",
    "verify_heap",
    "verify_hal",
    "macro_translate",
    "verify_lockfree",
    "verify_weak_memory",
    "verify_wcet",
    "verify_liveness",
    "verify_dma",
    "extract_intrusive_list",
    "resolve_callbacks",
    "submit_work_item",
    "get_work_item",
    "get_work_artifacts",
    "cancel_work_item",
    "start_agent_run",
    "get_agent_run",
    "resume_agent_run",
    "cancel_agent_run",
)

_GENERIC_DATA = [{'name': 'verify_code',
  'description': 'verify code',
  'cli_command': 'verify',
  'mcp_tool': 'verify_code',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'mcp_isolation': 'strict-execution',
  'mcp_profiles': ({'name': 'java-openjml-verification',
                    'modes': ('parse', 'check', 'esc'),
                    'languages': ('java', 'jml'),
                    'backends': ('openjml',),
                    'effects': ('workspace_read', 'external_execution',
                                'evidence_publication'),
                    'providers': (),
                    'output_scope': 'immutable-evidence-only',
                    'evidence': 'execution-observation-and-terminal-manifest'},
                   {'name': 'rust-compiler-verification',
                    'modes': ('parse', 'check'),
                    'languages': ('rust',),
                    'backends': ('rustc',),
                    'effects': ('workspace_read', 'external_execution',
                                'evidence_publication'),
                    'providers': (),
                    'output_scope': 'immutable-evidence-only',
                    'evidence': 'execution-observation-and-terminal-manifest'},
                   {'name': 'rust-prusti-verification',
                    'modes': ('esc',),
                    'languages': ('rust',),
                    'backends': ('prusti',),
                    'effects': ('workspace_read', 'external_execution',
                                'evidence_publication'),
                    'providers': (),
                    'output_scope': 'immutable-evidence-only',
                    'evidence': 'execution-observation-and-terminal-manifest'},
                   {'name': 'rust-kani-verification',
                    'modes': ('esc',),
                    'languages': ('rust',),
                    'backends': ('kani',),
                    'effects': ('workspace_read', 'external_execution',
                                'evidence_publication'),
                    'providers': (),
                    'output_scope': 'immutable-evidence-only',
                    'evidence': 'bounded-execution-observation-and-terminal-manifest'},
                   {'name': 'c-framac-verification',
                    'modes': ('esc',),
                    'languages': ('c',),
                    'backends': ('frama-c',),
                    'effects': ('workspace_read', 'external_execution',
                                'evidence_publication'),
                    'providers': (),
                    'output_scope': 'immutable-evidence-only',
                    'evidence': 'execution-observation-and-terminal-manifest'},
                   {'name': 'cpp-esbmc-verification',
                    'modes': ('esc',),
                    'languages': ('cpp',),
                    'backends': ('esbmc',),
                    'effects': ('workspace_read', 'external_execution',
                                'evidence_publication'),
                   'providers': (),
                    'output_scope': 'immutable-evidence-only',
                    'evidence': 'bounded-execution-observation-and-terminal-manifest'},
                   {'name': 'c-unsupported-mode-rejection',
                    'modes': ('parse', 'check'),
                    'languages': ('c',),
                    'backends': ('frama-c',),
                    'effects': ('workspace_read', 'evidence_publication'),
                    'providers': (),
                    'output_scope': 'immutable-evidence-only',
                    'evidence': 'structured-unsupported-mode-rejection'},
                   {'name': 'c-unsupported-mode-rejection-export',
                    'modes': ('parse', 'check'),
                    'languages': ('c',),
                    'backends': ('frama-c',),
                    'effects': ('workspace_read', 'evidence_publication',
                                'workspace_write_new'),
                    'required_effects': ('workspace_read', 'evidence_publication',
                                         'workspace_write_new'),
                    'providers': (),
                    'output_scope': 'designated-new-artifacts',
                    'evidence': 'structured-unsupported-mode-rejection-and-export'},
                   {'name': 'cpp-unsupported-mode-rejection',
                    'modes': ('parse', 'check'),
                    'languages': ('cpp',),
                    'backends': ('esbmc',),
                    'effects': ('workspace_read', 'evidence_publication'),
                    'providers': (),
                    'output_scope': 'immutable-evidence-only',
                    'evidence': 'structured-unsupported-mode-rejection'},
                   {'name': 'cpp-unsupported-mode-rejection-export',
                    'modes': ('parse', 'check'),
                    'languages': ('cpp',),
                    'backends': ('esbmc',),
                    'effects': ('workspace_read', 'evidence_publication',
                                'workspace_write_new'),
                    'required_effects': ('workspace_read', 'evidence_publication',
                                         'workspace_write_new'),
                    'providers': (),
                    'output_scope': 'designated-new-artifacts',
                    'evidence': 'structured-unsupported-mode-rejection-and-export'},
                   {'name': 'java-openjml-verification-export',
                    'modes': ('parse', 'check', 'esc'),
                    'languages': ('java', 'jml'),
                    'backends': ('openjml',),
                    'effects': ('workspace_read', 'external_execution',
                                'evidence_publication', 'workspace_write_new'),
                    'required_effects': ('workspace_read', 'external_execution',
                                         'evidence_publication', 'workspace_write_new'),
                    'providers': (),
                    'output_scope': 'designated-new-artifacts',
                    'evidence': 'execution-observation-terminal-manifest-and-export'},
                   {'name': 'rust-compiler-verification-export',
                    'modes': ('parse', 'check'),
                    'languages': ('rust',),
                    'backends': ('rustc',),
                    'effects': ('workspace_read', 'external_execution',
                                'evidence_publication', 'workspace_write_new'),
                    'required_effects': ('workspace_read', 'external_execution',
                                         'evidence_publication', 'workspace_write_new'),
                    'providers': (),
                    'output_scope': 'designated-new-artifacts',
                    'evidence': 'execution-observation-terminal-manifest-and-export'},
                   {'name': 'rust-prusti-verification-export',
                    'modes': ('esc',),
                    'languages': ('rust',),
                    'backends': ('prusti',),
                    'effects': ('workspace_read', 'external_execution',
                                'evidence_publication', 'workspace_write_new'),
                    'required_effects': ('workspace_read', 'external_execution',
                                         'evidence_publication', 'workspace_write_new'),
                    'providers': (),
                    'output_scope': 'designated-new-artifacts',
                    'evidence': 'execution-observation-terminal-manifest-and-export'},
                   {'name': 'rust-kani-verification-export',
                    'modes': ('esc',),
                    'languages': ('rust',),
                    'backends': ('kani',),
                    'effects': ('workspace_read', 'external_execution',
                                'evidence_publication', 'workspace_write_new'),
                    'required_effects': ('workspace_read', 'external_execution',
                                         'evidence_publication', 'workspace_write_new'),
                    'providers': (),
                    'output_scope': 'designated-new-artifacts',
                    'evidence': 'bounded-execution-observation-terminal-manifest-and-export'},
                   {'name': 'c-framac-verification-export',
                    'modes': ('esc',),
                    'languages': ('c',),
                    'backends': ('frama-c',),
                    'effects': ('workspace_read', 'external_execution',
                                'evidence_publication', 'workspace_write_new'),
                    'required_effects': ('workspace_read', 'external_execution',
                                         'evidence_publication', 'workspace_write_new'),
                    'providers': (),
                    'output_scope': 'designated-new-artifacts',
                    'evidence': 'execution-observation-terminal-manifest-and-export'},
                   {'name': 'cpp-esbmc-verification-export',
                    'modes': ('esc',),
                    'languages': ('cpp',),
                    'backends': ('esbmc',),
                    'effects': ('workspace_read', 'external_execution',
                                'evidence_publication', 'workspace_write_new'),
                    'required_effects': ('workspace_read', 'external_execution',
                                         'evidence_publication', 'workspace_write_new'),
                    'providers': (),
                    'output_scope': 'designated-new-artifacts',
                    'evidence': 'bounded-execution-observation-terminal-manifest-and-export'}),
  'milestone': None},
 {'name': 'validate_architecture',
  'description': 'validate architecture',
  'cli_command': 'validate-architecture',
  'mcp_tool': 'validate_architecture',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'implement_code',
  'description': 'implement code',
  'cli_command': 'implement',
  'mcp_tool': 'implement_code',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'inspect_code',
  'description': 'inspect code',
  'cli_command': 'inspect',
  'mcp_tool': 'inspect_code',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'mcp_isolation': 'non-executing',
  'mcp_profiles': ({'name': 'java-readonly-inspection',
                    'modes': ('inspect',),
                    'languages': ('java', 'jml'),
                    'backends': ('builtin-java-inspector',),
                    'effects': ('workspace_read',),
                    'providers': (),
                    'output_scope': 'none',
                    'evidence': 'structured-findings'},
                   {'name': 'java-inspection-export',
                    'modes': ('inspect',),
                    'languages': ('java', 'jml'),
                    'backends': ('builtin-java-inspector',),
                    'effects': ('workspace_read', 'workspace_write_new'),
                    'providers': (),
                    'output_scope': 'designated-new-artifacts',
                    'evidence': 'unreviewed-structured-inspection-export'}),
  'milestone': None},
 {'name': 'analyze_codebase',
  'description': 'analyze codebase',
  'cli_command': 'analyze-codebase',
  'mcp_tool': 'analyze_codebase',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'document_code',
  'description': ('Generate unreviewed Java documentation deterministically or '
                  'through an explicitly approved provider; no external execution.'),
  'cli_command': 'document-code',
  'mcp_tool': 'document_code',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'mcp_isolation': 'non-executing',
  'mcp_profiles': ({'name': 'java-deterministic-documentation',
                    'modes': ('deterministic',),
                    'languages': ('java',),
                    'backends': ('builtin-documentation',),
                    'effects': ('workspace_read', 'workspace_write_new'),
                    'providers': (),
                    'output_scope': 'designated-new-artifacts',
                    'evidence': 'unreviewed-documentation'},
                   {'name': 'java-provider-assisted-documentation',
                    'modes': ('provider-assisted',),
                    'languages': ('java',),
                    'backends': ('builtin-documentation',),
                    'effects': ('workspace_read', 'workspace_write_new',
                                'provider_access'),
                    'providers': ('glm', 'openai', 'ollama'),
                    'output_scope': 'designated-new-artifacts',
                    'evidence': 'unreviewed-provider-documentation'}),
  'milestone': None},
 {'name': 'submit_work_item',
  'description': ('Submit an authority-bound implementation proposal to an '
                  'operator-approved A2A worker.'),
  'cli_command': None,
  'mcp_tool': 'submit_work_item',
  'arguments': (),
  'epistemic_boundary': ('Worker completion produces a proposal only; it is not '
                         'acceptance, proof, or merge authority.'),
  'trust_action': False,
  'mcp_isolation': 'a2a-coordination',
  'mcp_profiles': ({'name': 'a2a-submit-proposal',
                    'modes': ('submit',),
                    'languages': ('none',),
                    'backends': ('a2a-1.0',),
                    'effects': ('workspace_read', 'service_state_write',
                                'remote_worker_dispatch'),
                    'required_effects': ('workspace_read', 'service_state_write',
                                         'remote_worker_dispatch'),
                    'providers': (),
                    'output_scope': 'none',
                    'evidence': 'append-only-worker-task-events'},),
  'milestone': None},
 {'name': 'get_work_item',
  'description': 'Read and optionally refresh an authorized A2A work item.',
  'cli_command': None,
  'mcp_tool': 'get_work_item',
  'arguments': (),
  'epistemic_boundary': 'Worker task state never implies implementation acceptance.',
  'trust_action': False,
  'mcp_isolation': 'a2a-coordination',
  'mcp_profiles': ({'name': 'a2a-read-task',
                    'modes': ('local',),
                    'languages': ('none',),
                    'backends': ('a2a-1.0',),
                    'effects': ('service_state_read',),
                    'required_effects': ('service_state_read',),
                    'providers': (),
                    'output_scope': 'none',
                    'evidence': 'append-only-worker-task-events'},
                   {'name': 'a2a-refresh-task',
                    'modes': ('refresh',),
                    'languages': ('none',),
                    'backends': ('a2a-1.0',),
                    'effects': ('service_state_read', 'service_state_write',
                                'remote_worker_dispatch'),
                    'required_effects': ('service_state_read', 'service_state_write',
                                         'remote_worker_dispatch'),
                    'providers': (),
                    'output_scope': 'none',
                    'evidence': 'append-only-worker-task-events'}),
  'milestone': None},
 {'name': 'get_work_artifacts',
  'description': 'Retrieve digest-bound artifact references for an authorized work item.',
  'cli_command': None,
  'mcp_tool': 'get_work_artifacts',
  'arguments': (),
  'epistemic_boundary': 'Artifact references remain unaccepted worker output.',
  'trust_action': False,
  'mcp_isolation': 'a2a-coordination',
  'mcp_profiles': ({'name': 'a2a-read-artifact-references',
                    'modes': ('artifacts',),
                    'languages': ('none',),
                    'backends': ('a2a-1.0',),
                    'effects': ('service_state_read',),
                    'required_effects': ('service_state_read',),
                    'providers': (),
                    'output_scope': 'none',
                    'evidence': 'digest-bound-worker-artifact-references'},),
  'milestone': None},
 {'name': 'cancel_work_item',
  'description': 'Request cancellation of an authorized A2A work item.',
  'cli_command': None,
  'mcp_tool': 'cancel_work_item',
  'arguments': (),
  'epistemic_boundary': 'Cancellation is a task outcome, not a verification result.',
  'trust_action': False,
  'mcp_isolation': 'a2a-coordination',
  'mcp_profiles': ({'name': 'a2a-cancel-task',
                    'modes': ('cancel',),
                    'languages': ('none',),
                    'backends': ('a2a-1.0',),
                    'effects': ('service_state_read', 'service_state_write',
                                'remote_worker_dispatch'),
                    'required_effects': ('service_state_read', 'service_state_write',
                                         'remote_worker_dispatch'),
                    'providers': (),
                    'output_scope': 'none',
                    'evidence': 'append-only-worker-task-events'},),
  'milestone': None},
 {'name': 'start_agent_run',
  'description': ('Start a supervised inspect-and-verify goal over one approved '
                  'Java/JML source snapshot.'),
  'cli_command': None,
  'mcp_tool': 'start_agent_run',
  'arguments': (),
  'epistemic_boundary': ('The supervisor selects only admitted inspection and '
                         'verification actions; it cannot edit, approve, sign, or merge.'),
  'trust_action': False,
  'mcp_isolation': 'strict-execution',
  'mcp_profiles': ({'name': 'supervised-java-inspect-verify',
                    'modes': ('supervise',),
                    'languages': ('java', 'jml'),
                    'backends': ('openjml',),
                    'effects': ('workspace_read', 'external_execution',
                                'evidence_publication', 'service_state_read',
                                'service_state_write'),
                    'required_effects': ('workspace_read', 'external_execution',
                                         'evidence_publication', 'service_state_read',
                                         'service_state_write'),
                    'providers': (),
                    'output_scope': 'immutable-evidence-only',
                    'evidence': 'agent-review-and-child-manifests'},),
  'milestone': None},
 {'name': 'get_agent_run',
  'description': 'Read a principal-owned supervised agent run without resuming it.',
  'cli_command': None,
  'mcp_tool': 'get_agent_run',
  'arguments': (),
  'epistemic_boundary': 'Reading run state grants no workflow or trust authority.',
  'trust_action': False,
  'mcp_isolation': 'non-executing',
  'mcp_profiles': ({'name': 'read-supervised-agent-run',
                    'modes': ('local',),
                    'languages': ('none',),
                    'backends': ('builtin-supervisor',),
                    'effects': ('service_state_read',),
                    'required_effects': ('service_state_read',),
                    'providers': (),
                    'output_scope': 'none',
                    'evidence': 'append-only-agent-run-events'},),
  'milestone': None},
 {'name': 'resume_agent_run',
  'description': 'Resume a principal-owned supervised run between known actions.',
  'cli_command': None,
  'mcp_tool': 'resume_agent_run',
  'arguments': (),
  'epistemic_boundary': ('An interrupted action is never replayed automatically; '
                         'unknown outcomes block for reconciliation.'),
  'trust_action': False,
  'mcp_isolation': 'strict-execution',
  'mcp_profiles': ({'name': 'resume-supervised-java-inspect-verify',
                    'modes': ('resume',),
                    'languages': ('none',),
                    'backends': ('builtin-supervisor',),
                    'effects': ('workspace_read', 'external_execution',
                                'evidence_publication', 'service_state_read',
                                'service_state_write'),
                    'required_effects': ('workspace_read', 'external_execution',
                                         'evidence_publication', 'service_state_read',
                                         'service_state_write'),
                    'providers': (),
                    'output_scope': 'immutable-evidence-only',
                    'evidence': 'agent-review-and-child-manifests'},),
  'milestone': None},
 {'name': 'cancel_agent_run',
  'description': 'Request cancellation of a principal-owned supervised agent run.',
  'cli_command': None,
  'mcp_tool': 'cancel_agent_run',
  'arguments': (),
  'epistemic_boundary': 'Cancellation is a run outcome and never a proof claim.',
  'trust_action': False,
  'mcp_isolation': 'non-executing',
  'mcp_profiles': ({'name': 'cancel-supervised-agent-run',
                    'modes': ('cancel',),
                    'languages': ('none',),
                    'backends': ('builtin-supervisor',),
                    'effects': ('service_state_read', 'service_state_write',
                                'evidence_publication'),
                    'required_effects': ('service_state_read', 'service_state_write',
                                         'evidence_publication'),
                    'providers': (),
                    'output_scope': 'none',
                    'evidence': 'append-only-agent-run-events'},),
  'milestone': None},
 {'name': 'assess_security',
  'description': 'assess security',
  'cli_command': 'assess-security',
  'mcp_tool': 'assess_security',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'security_inspect',
  'description': 'security inspect',
  'cli_command': 'security-inspect',
  'mcp_tool': 'security_inspect',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'security_exploit',
  'description': 'security exploit',
  'cli_command': 'security-exploit',
  'mcp_tool': 'security_exploit',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'remediate_code',
  'description': 'remediate code',
  'cli_command': 'remediate',
  'mcp_tool': 'remediate_code',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'correct_behavior',
  'description': 'correct behavior',
  'cli_command': 'correct-behavior',
  'mcp_tool': 'correct_behavior',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'apply_refactor',
  'description': 'apply refactor',
  'cli_command': 'apply-refactor',
  'mcp_tool': 'apply_refactor',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'verify_refactor',
  'description': ('Prove that independently checked baseline and candidate '
                  'artifacts preserve the reviewed contract surface.'),
  'cli_command': 'verify-refactor',
  'mcp_tool': 'verify_refactor',
  'arguments': (),
  'epistemic_boundary': ('Preservation binds both revisions and actual backend '
                         'observations; signing remains human-authorized.'),
  'trust_action': False,
  'mcp_isolation': 'strict-execution',
  'mcp_profiles': (
      {'name': 'java-openjml-refactor-preservation',
       'modes': ('preserve',), 'languages': ('java', 'jml'),
       'backends': ('openjml',),
       'effects': ('workspace_read', 'external_execution',
                   'evidence_publication'),
       'required_effects': ('workspace_read', 'external_execution',
                            'evidence_publication'),
       'providers': (), 'output_scope': 'immutable-evidence-only',
       'evidence': 'baseline-candidate-observations-and-terminal-manifest'},
      {'name': 'rust-prusti-refactor-preservation',
       'modes': ('preserve',), 'languages': ('rust',),
       'backends': ('prusti',),
       'effects': ('workspace_read', 'external_execution',
                   'evidence_publication'),
       'required_effects': ('workspace_read', 'external_execution',
                            'evidence_publication'),
       'providers': (), 'output_scope': 'immutable-evidence-only',
       'evidence': 'baseline-candidate-observations-and-terminal-manifest'},
      {'name': 'c-framac-refactor-preservation',
       'modes': ('preserve',), 'languages': ('c',),
       'backends': ('frama-c',),
       'effects': ('workspace_read', 'external_execution',
                   'evidence_publication'),
       'required_effects': ('workspace_read', 'external_execution',
                            'evidence_publication'),
       'providers': (), 'output_scope': 'immutable-evidence-only',
       'evidence': 'baseline-candidate-observations-and-terminal-manifest'},
      {'name': 'cpp-esbmc-refactor-preservation',
       'modes': ('preserve',), 'languages': ('cpp',),
       'backends': ('esbmc',),
       'effects': ('workspace_read', 'external_execution',
                   'evidence_publication'),
       'required_effects': ('workspace_read', 'external_execution',
                            'evidence_publication'),
       'providers': (), 'output_scope': 'immutable-evidence-only',
       'evidence': 'bounded-baseline-candidate-observations-and-terminal-manifest'},
      {'name': 'java-openjml-refactor-preservation-export',
       'modes': ('preserve',), 'languages': ('java', 'jml'),
       'backends': ('openjml',),
       'effects': ('workspace_read', 'external_execution',
                   'evidence_publication', 'workspace_write_new'),
       'required_effects': ('workspace_read', 'external_execution',
                            'evidence_publication', 'workspace_write_new'),
       'providers': (), 'output_scope': 'designated-new-artifacts',
       'evidence': 'baseline-candidate-observations-terminal-manifest-and-export'},
      {'name': 'rust-prusti-refactor-preservation-export',
       'modes': ('preserve',), 'languages': ('rust',),
       'backends': ('prusti',),
       'effects': ('workspace_read', 'external_execution',
                   'evidence_publication', 'workspace_write_new'),
       'required_effects': ('workspace_read', 'external_execution',
                            'evidence_publication', 'workspace_write_new'),
       'providers': (), 'output_scope': 'designated-new-artifacts',
       'evidence': 'baseline-candidate-observations-terminal-manifest-and-export'},
      {'name': 'c-framac-refactor-preservation-export',
       'modes': ('preserve',), 'languages': ('c',),
       'backends': ('frama-c',),
       'effects': ('workspace_read', 'external_execution',
                   'evidence_publication', 'workspace_write_new'),
       'required_effects': ('workspace_read', 'external_execution',
                            'evidence_publication', 'workspace_write_new'),
       'providers': (), 'output_scope': 'designated-new-artifacts',
       'evidence': 'baseline-candidate-observations-terminal-manifest-and-export'},
      {'name': 'cpp-esbmc-refactor-preservation-export',
       'modes': ('preserve',), 'languages': ('cpp',),
       'backends': ('esbmc',),
       'effects': ('workspace_read', 'external_execution',
                   'evidence_publication', 'workspace_write_new'),
       'required_effects': ('workspace_read', 'external_execution',
                            'evidence_publication', 'workspace_write_new'),
       'providers': (), 'output_scope': 'designated-new-artifacts',
       'evidence': ('bounded-baseline-candidate-observations-terminal-manifest-'
                    'and-export')}),
  'milestone': None},
 {'name': 'verify_bisimulation',
  'description': 'verify bisimulation',
  'cli_command': 'verify-bisimulation',
  'mcp_tool': 'verify_bisimulation',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'optimize_algorithm',
  'description': 'optimize algorithm',
  'cli_command': 'optimize-algorithm',
  'mcp_tool': 'optimize_algorithm',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'discover_algorithms',
  'description': 'discover algorithms',
  'cli_command': 'discover-algorithms',
  'mcp_tool': 'discover_algorithms',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'validate_domain',
  'description': 'validate domain',
  'cli_command': 'validate-domain',
  'mcp_tool': 'validate_domain',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'compose',
  'description': 'compose',
  'cli_command': 'compose',
  'mcp_tool': 'compose',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'reverify_composition',
  'description': 'reverify composition',
  'cli_command': 'reverify',
  'mcp_tool': 'reverify_composition',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'unified_system',
  'description': 'unified system',
  'cli_command': 'unified-system',
  'mcp_tool': 'unified_system',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'draft_canonical_contract',
  'description': 'draft canonical contract',
  'cli_command': None,
  'mcp_tool': 'draft_canonical_contract',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'architecture',
  'description': 'architecture',
  'cli_command': 'architecture',
  'mcp_tool': 'architecture',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'system',
  'description': 'system',
  'cli_command': 'system',
  'mcp_tool': 'system',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'prove_equivalence',
  'description': 'prove equivalence',
  'cli_command': 'prove-equivalence',
  'mcp_tool': 'prove_equivalence',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'generate_traceability_matrix',
  'description': 'generate traceability matrix',
  'cli_command': 'generate-traceability-matrix',
  'mcp_tool': 'generate_traceability_matrix',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'verify_unbounded',
  'description': 'verify unbounded',
  'cli_command': 'verify-unbounded',
  'mcp_tool': 'verify_unbounded',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'verify_linearizability',
  'description': 'verify linearizability',
  'cli_command': 'verify-linearizability',
  'mcp_tool': 'verify_linearizability',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'verify_distributed',
  'description': 'verify distributed',
  'cli_command': 'verify-distributed',
  'mcp_tool': 'verify_distributed',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'verify_heap',
  'description': 'verify heap',
  'cli_command': 'verify-heap',
  'mcp_tool': 'verify_heap',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'verify_hal',
  'description': 'verify hal',
  'cli_command': 'verify-hal',
  'mcp_tool': 'verify_hal',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'macro_translate',
  'description': 'macro translate',
  'cli_command': None,
  'mcp_tool': 'macro_translate',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'verify_lockfree',
  'description': 'verify lockfree',
  'cli_command': 'verify-lockfree',
  'mcp_tool': 'verify_lockfree',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'verify_weak_memory',
  'description': 'verify weak memory',
  'cli_command': None,
  'mcp_tool': 'verify_weak_memory',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'verify_wcet',
  'description': 'verify wcet',
  'cli_command': None,
  'mcp_tool': 'verify_wcet',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'verify_liveness',
  'description': 'verify liveness',
  'cli_command': None,
  'mcp_tool': 'verify_liveness',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'verify_dma',
  'description': 'verify dma',
  'cli_command': None,
  'mcp_tool': 'verify_dma',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'extract_intrusive_list',
  'description': 'extract intrusive list',
  'cli_command': None,
  'mcp_tool': 'extract_intrusive_list',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'resolve_callbacks',
  'description': 'resolve callbacks',
  'cli_command': None,
  'mcp_tool': 'resolve_callbacks',
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': False,
  'milestone': None},
 {'name': 'doctor',
  'description': 'Report judge readiness and evidence ceilings.',
  'cli_command': 'doctor',
  'mcp_tool': 'doctor_environment',
  'arguments': (),
  'epistemic_boundary': 'Always claim=NO_PROOF.',
  'trust_action': False,
  'milestone': None},
 {'name': 'promote_domain',
  'description': 'Human acceptance of reviewed evidence.',
  'cli_command': 'promote-domain',
  'mcp_tool': None,
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': True,
  'milestone': None},
 {'name': 'sign_artifact',
  'description': 'Human reviewer signature action.',
  'cli_command': 'sign-artifact',
  'mcp_tool': None,
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': True,
  'milestone': None},
 {'name': 'manage_trust',
  'description': 'Human reviewer key-policy action.',
  'cli_command': 'manage-trust',
  'mcp_tool': None,
  'arguments': (),
  'epistemic_boundary': 'No claim is minted without its named judge.',
  'trust_action': True,
  'milestone': None},
 {'name': 'm55_vfs',
  'description': 'Bounded VFS state machine, inode cache, and Rust refinement lane.',
  'cli_command': None,
  'mcp_tool': None,
  'arguments': (),
  'epistemic_boundary': 'Extraction never implies refinement; production requires the hash-bound '
                        'native gate in deliverable 4.',
  'trust_action': False,
  'milestone': {'lane': 'M55_vfs',
                'deployment_split': 'shared_algorithmic',
                'required_judges': ('TLC', 'Prusti', 'Z3'),
                'claims': ({'claim': 'BOUNDED_ARCHITECTURE_EVIDENCE', 'minimum_step': 3},
                           {'claim': 'SOURCE_MODEL_REFINEMENT', 'minimum_step': 4},
                           {'claim': 'HARDWARE_MEMORY_BOUND_PROVED', 'minimum_step': 4}),
                'claims_forbidden': ('SOURCE_MODEL_REFINEMENT_WITHOUT_NATIVE_GATE',
                                     'HARDWARE_MEMORY_BOUND_PROVED_WITHOUT_PROFILE_BOUND_POOL',
                                     'PRODUCTION_UNTIL_ALL_STEP_4_GATES'),
                'assumptions': ('hardware_page_table_walker:judge_pending',
                                'DMA physical isolation belongs to M39/M56'),
                'deployment_profiles': ('microkernel', 'monolith'),
                'hardware_profiles': ('n150', 'r52'),
                'artifact_hash_bindings': ('domains/candidates/vfs_bounded.v2.yaml',
                                           'domains/candidates/vfs_bounded.v2.validation.json',
                                           'domains/v2/vfs_bounded.json',
                                           'domains/v2/vfs_bounded.rust-refinement.yaml',
                                           'Vfs.rs'),
                'maturity_from': 'scaffold',
                'maturity_to': 'production',
                'maturity_requires_step': 4,
                'current_step': 4,
                'step_status': 'complete',
                'current_maturity': 'production',
                'completed_claims': ('BOUNDED_ARCHITECTURE_EVIDENCE',
                                     'SOURCE_MODEL_REFINEMENT',
                                     'HARDWARE_MEMORY_BOUND_PROVED')}}]

CAPABILITIES: tuple[CapabilitySpec, ...] = tuple(
    _capability(item) for item in _GENERIC_DATA
)


def capability(name: str) -> CapabilitySpec:
    matches = [item for item in CAPABILITIES if item.name == name]
    if len(matches) != 1:
        raise KeyError(f"capability registry expected exactly one {name!r} entry")
    return matches[0]


def mcp_capabilities(*, strict_isolation: bool = False) -> tuple[CapabilitySpec, ...]:
    capabilities = tuple(
        item for item in CAPABILITIES if item.mcp_tool and not item.trust_action
    )
    if not strict_isolation:
        return capabilities
    return tuple(
        item
        for item in capabilities
        if item.mcp_isolation in {
            "a2a-coordination", "non-executing", "strict-java",
            "strict-execution"}
        and item.mcp_profiles
    )


def milestone_capabilities() -> tuple[CapabilitySpec, ...]:
    return tuple(item for item in CAPABILITIES if item.milestone is not None)


def add_cli_parser(
    subparsers: argparse._SubParsersAction, name: str
) -> argparse.ArgumentParser:
    spec = capability(name)
    if spec.cli_command is None or not spec.arguments:
        raise ValueError(f"capability {name!r} has no generated CLI schema")
    parser = subparsers.add_parser(spec.cli_command, help=spec.description)
    for argument in spec.arguments:
        parser.add_argument(*argument.flags, **argument.kwargs)
    return parser
