// UNVERIFIED EXTERNAL BOUNDARY: generated integration stub.
public class StripePaymentGateway implements PaymentGateway {
    //@ requires amount > 0;
    //@ ensures result = true or result = false;
    public boolean processPayment(int amount) {
        try {
            // Create a charge using Stripe's Java SDK
            java.util.Map<String, Object> chargeParams = new java.util.HashMap<>();
            chargeParams.put("amount", amount);
            chargeParams.put("currency", "usd");
            
            // Using a mock card token for demonstration - in reality this would be 
            // generated by Stripe.js or another client-side integration
            chargeParams.put("source", "tok_visa"); 
            
            com.stripe.model.Charge charge = com.stripe.model.Charge.create(chargeParams);
            return charge != null && "succeeded".equals(charge.getStatus());
        } catch (com.stripe.exception.StripeException e) {
            // In a real implementation, this would be logged appropriately
            return false;
        }
    }
}
